from __future__ import annotations

__all__ = (
    "alert",
    "input_alert",
    "login_alert",
    "password_alert",
    "hud_alert",
)

def clear(): ...
def set_font(name, size): ...
def set_color(r, g, b): ...
def secure_input(prompt): ...
def show_image(image_path): ...
def alert(
    title: str,
    message: str | None = None,
    button1: str | None = None,
    button2: str | None = None,
    button3: str | None = None,
    hide_cancel_button: bool = False,
): ...
def input_alert(
    title: str,
    message: str | None = None,
    input=None,
    ok_button_title: str | None = None,
    hide_cancel_button: bool = False,
): ...
def password_alert(
    title: str,
    message: str | None = None,
    password: str | None = None,
    ok_button_title: str | None = None,
    hide_cancel_button: bool = False,
): ...
def login_alert(
    title: str,
    message: str | None = None,
    password: str | None = None,
    ok_button_title: str | None = None,
): ...
def show_activity(): ...
def hide_activity(): ...
def hud_alert(message, icon, duration): ...
def write_link(title, link_url): ...
def hide_output(): ...
def quicklook(file_path): ...
def open_in(file_path): ...
def set_idle_timer_disabled(flag): ...
def is_in_background(): ...
